import type { NewsItem } from './redis';

export const MOCK_ITEMS: NewsItem[] = [
  {
    id: 'mock-1',
    title: 'Global climate summit reaches landmark agreement',
    link: 'https://example.com/1',
    source: 'reuters.com',
    lat: 48.85,
    lon: 2.35,
    publishedAt: Date.now() - 2 * 60 * 1000,
  },
  {
    id: 'mock-2',
    title: 'Tech giants announce new AI safety framework',
    link: 'https://example.com/2',
    source: 'bbc.co.uk',
    lat: 37.78,
    lon: -122.42,
    publishedAt: Date.now() - 5 * 60 * 1000,
  },
  {
    id: 'mock-3',
    title: 'UN Security Council holds emergency session',
    link: 'https://example.com/3',
    source: 'apnews.com',
    lat: 40.75,
    lon: -73.99,
    publishedAt: Date.now() - 8 * 60 * 1000,
  },
  {
    id: 'mock-4',
    title: 'Markets rally on positive economic data from Asia',
    link: 'https://example.com/4',
    source: 'ft.com',
    lat: 35.69,
    lon: 139.69,
    publishedAt: Date.now() - 12 * 60 * 1000,
  },
  {
    id: 'mock-5',
    title: 'Earthquake strikes coastal region, aid teams mobilized',
    link: 'https://example.com/5',
    source: 'aljazeera.com',
    lat: -8.34,
    lon: 115.09,
    publishedAt: Date.now() - 18 * 60 * 1000,
  },
  {
    id: 'mock-6',
    title: 'Record heat wave sweeps across Mediterranean',
    link: 'https://example.com/6',
    source: 'guardian.com',
    lat: 41.9,
    lon: 12.5,
    publishedAt: Date.now() - 25 * 60 * 1000,
  },
  {
    id: 'mock-7',
    title: 'Peace talks resume between rival factions',
    link: 'https://example.com/7',
    source: 'reuters.com',
    lat: 15.55,
    lon: 32.53,
    publishedAt: Date.now() - 35 * 60 * 1000,
  },
  {
    id: 'mock-8',
    title: 'New vaccine shows 95% efficacy in clinical trials',
    link: 'https://example.com/8',
    source: 'bbc.co.uk',
    lat: 51.5,
    lon: -0.12,
    publishedAt: Date.now() - 45 * 60 * 1000,
  },
];
